### PR TITLE
SPV validation fixups

### PR DESCRIPTION
**Pull request by shesek**
Followup to #66, a few more things I noticed while working on multi-server validation.

### CODE REVIEW

**Comment by shesek** [comment]
A similar issue to https://github.com/Blockstream/gdk/pull/69/commits/a71b8103c016848b6dd1f752cdfcf79801a50ba7 also exists with SPV validation through the C FFI. Failures to retrieve the merkle inclusion proof will result in `spv_verify_tx()` failing with an `Err` and `GDKRUST_spv_verify_tx` returning `-1` rather than the `NotVerified` status.

I'll change this too, but its probably a good idea to also make sure that the CPP side handles `-1` codes properly (treating it similarly to `NotVerified` I guess?).

**Comment by RCasatta** [comment]
I don't like too much `NotVerified` for errors that could be network transient errors maybe we can have also something like `NetworkError`.

But maybe is due to my interpretation of the variant, I think we have to doc comment the SPVVerifyResult variants to be more objective

**Comment by shesek** [comment]
The case that I've been running into is that the primary server no longer considers the transaction to be confirmed, and so doesn't return a merkle inclusion proof for it. At least for this, it makes sense to use `NotVerified`.

Perhaps we could differentiate between connections errors and rpc errors that indicate the proof is unavailable?

**Comment by RCasatta** [comment]
my mistake I thought we were talking about get_merkle_proof error, and yes I think we should differentiate connection errors

**Comment by RCasatta** [comment]
ack f54a71e03914206e43891063a5689e80a5b44c21

**Pull request merged**
